# Generated by Django 4.2.9 on 2024-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pexpo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("A", "Automatic"), ("M", "Manual")], max_length=2
                    ),
                ),
            ],
        ),
    ]
