# Generated by Django 4.2.9 on 2024-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pexpo", "0002_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                max_length=10,
            ),
        ),
    ]
