# Generated by Django 4.2.9 on 2024-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pexpo", "0003_alter_car_transmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=50)),
                ("release_year", models.IntegerField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("G", "G"),
                            ("PG", "PG"),
                            ("PG-13", "PG-13"),
                            ("R", "R"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=50)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop", "Pop"),
                            ("Rock", "Rock"),
                            ("Hip Hop", "Hip Hop"),
                            ("Electronic", "Electronic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.FloatField()),
            ],
        ),
    ]
