# Generated by Django 4.2.9 on 2024-03-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pexpo", "0005_jobposting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                ],
                max_length=5,
            ),
        ),
    ]
