# Generated by Django 4.2.9 on 2024-03-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pexpo", "0009_postcategory_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pexpo.postcategory"
            ),
        ),
    ]
